/* auto-generated from ui.html — do not edit */
#ifndef AGATA_UI_H
#define AGATA_UI_H

static const char UI_HTML[] =
  "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>Agata PS5</title>\n<style>\n  :root{\n    --bg:#0f0f10; --panel:"
  "#16171b; --panel2:#1d1e24; --line:#2a2b33;\n    --text:#e8e8ea; --dim:#9a9ba3; --accent:#2d6cff; --accent2:#4c8bff;\n    --ok:#3fb950; --err:#f85149; --warn:#d29922; --radius:12px;\n  }\n  *{box-sizing:bo"
  "rder-box;margin:0;padding:0}\n  body{background:var(--bg);color:var(--text);font:14px/1.5 -apple-system,'Segoe UI',Roboto,sans-serif;min-height:100vh}\n  header{position:sticky;top:0;z-index:10;display:"
  "flex;align-items:center;gap:28px;padding:14px 28px;background:rgba(15,15,16,.92);backdrop-filter:blur(8px);border-bottom:1px solid var(--line)}\n  .brand{font-size:17px;font-weight:700;letter-spacing:."
  "12em;color:var(--accent2)}\n  nav{display:flex;gap:4px}\n  nav button{background:none;border:none;color:var(--dim);font:inherit;font-weight:600;padding:8px 16px;border-radius:8px;cursor:pointer}\n  nav b"
  "utton:hover{color:var(--text);background:var(--panel2)}\n  nav button.active{color:var(--text);background:var(--panel2)}\n  main{padding:24px 28px;max-width:1400px;margin:0 auto}\n  .row{display:flex;gap"
  ":10px;align-items:center;margin-bottom:18px;flex-wrap:wrap}\n  input[type=text]{background:var(--panel);border:1px solid var(--line);color:var(--text);border-radius:8px;padding:9px 14px;font:inherit;mi"
  "n-width:340px;flex:1}\n  input[type=text]:focus{outline:none;border-color:var(--accent)}\n  .btn{background:var(--accent);border:none;color:#fff;font:inherit;font-weight:600;padding:9px 18px;border-radi"
  "us:8px;cursor:pointer}\n  .btn:hover{background:var(--accent2)}\n  .btn.ghost{background:var(--panel2);color:var(--text)}\n  .btn.small{padding:5px 12px;font-size:12.5px}\n  .grid{display:grid;grid-templa"
  "te-columns:repeat(auto-fill,minmax(168px,1fr));gap:16px}\n  .card{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);overflow:hidden;cursor:pointer;transition:transform .1"
  "2s,border-color .12s}\n  .card:hover{transform:translateY(-3px);border-color:var(--accent)}\n  .card .poster{aspect-ratio:2/3;width:100%;object-fit:cover;background:var(--panel2);display:block}\n  .card "
  ".meta{padding:10px 12px}\n  .card .t{font-weight:600;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n  .card .s{color:var(--dim);font-size:11.5px;margin-top:2px}\n  .empty{colo"
  "r:var(--dim);padding:40px;text-align:center}\n  .panel{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);padding:20px}\n  table{width:100%;border-collapse:collapse}\n  th,t"
  "d{text-align:left;padding:9px 12px;border-bottom:1px solid var(--line);font-size:13.5px}\n  th{color:var(--dim);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.06em}\n  tr:hover "
  "td{background:var(--panel2)}\n  td .fname{color:var(--text);cursor:pointer}\n  td .fname.dir{color:var(--accent2);cursor:pointer}\n  .bar{height:7px;background:var(--panel2);border-radius:4px;overflow:hi"
  "dden;min-width:120px}\n  .bar i{display:block;height:100%;background:var(--accent);border-radius:4px;transition:width .4s}\n  .pill{display:inline-block;padding:2px 10px;border-radius:20px;font-size:11."
  "5px;font-weight:600}\n  .pill.ok{background:#12351c;color:var(--ok)} .pill.err{background:#3d1412;color:var(--err)}\n  .pill.run{background:#12233f;color:var(--accent2)} .pill.q{background:#2b230d;color"
  ":var(--warn)}\n  #detail{position:fixed;inset:0;background:rgba(0,0,0,.66);display:none;align-items:center;justify-content:center;z-index:20}\n  #detail .box{background:var(--panel);border:1px solid var"
  "(--line);border-radius:16px;max-width:680px;width:92%;max-height:86vh;overflow:auto;padding:24px}\n  #detail h2{margin-bottom:4px} #detail .sub{color:var(--dim);margin-bottom:14px;font-size:12.5px}\n  #"
  "detail pre{white-space:pre-wrap;background:var(--panel2);border-radius:8px;padding:12px;font-size:12px;margin:12px 0;color:var(--dim)}\n  .linkrow{display:flex;justify-content:space-between;align-items"
  ":center;gap:12px;padding:8px 0;border-bottom:1px solid var(--line)}\n  .linkrow .n{font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n  .crumbs{color:var(--dim);font-size:13px;ma"
  "rgin-bottom:12px;word-break:break-all}\n  .crumbs b{color:var(--text)}\n  .stat{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}\n  .stat .kv{background:var(--panel);border"
  ":1px solid var(--line);border-radius:var(--radius);padding:16px}\n  .stat .k{color:var(--dim);font-size:11.5px;text-transform:uppercase;letter-spacing:.06em}\n  .stat .v{font-size:16px;font-weight:600;m"
  "argin-top:4px}\n  .flash{position:fixed;bottom:20px;right:20px;background:var(--panel2);border:1px solid var(--accent);border-radius:10px;padding:12px 18px;display:none;z-index:30}\n</style>\n</head>\n<bo"
  "dy>\n<header>\n  <div class=\"brand\">AGATA&nbsp;PS5</div>\n  <nav>\n    <button data-tab=\"store\" class=\"active\">Store</button>\n    <button data-tab=\"files\">Files</button>\n    <button data-tab=\"downloads\">D"
  "ownloads</button>\n    <button data-tab=\"status\">Status</button>\n  </nav>\n</header>\n<main>\n  <section id=\"tab-store\">\n    <div class=\"row\">\n      <select id=\"catsel\" onchange=\"pickCatalog()\" style=\"bac"
  "kground:var(--panel);border:1px solid var(--line);color:var(--text);border-radius:8px;padding:9px 12px;font:inherit\"></select>\n      <input type=\"text\" id=\"caturl\" placeholder=\"Catalog JSON URL\">\n    "
  "  <button class=\"btn\" onclick=\"loadCatalog()\">Load</button>\n      <input type=\"text\" id=\"q\" placeholder=\"Search…\" style=\"min-width:200px;flex:0 0 260px\" oninput=\"renderStore()\">\n      <span id=\"catinf"
  "o\" style=\"color:var(--dim)\"></span>\n    </div>\n    <div id=\"storegrid\" class=\"grid\"></div>\n  </section>\n\n  <section id=\"tab-files\" style=\"display:none\">\n    <div id=\"dualpane\" style=\"display:grid;grid"
  "-template-columns:1fr 1fr;gap:16px\"></div>\n  </section>\n\n  <section id=\"tab-downloads\" style=\"display:none\">\n    <div class=\"row\">\n      <input type=\"text\" id=\"manualurl\" placeholder=\"Direct URL to do"
  "wnload (http)\">\n      <input type=\"text\" id=\"manualdest\" placeholder=\"/mnt/usb0\" style=\"flex:0 0 220px\">\n      <button class=\"btn\" onclick=\"queueManual()\">Queue</button>\n    </div>\n    <div class=\"pan"
  "el\"><table><thead><tr><th>#</th><th>URL</th><th style=\"width:90px\">Status</th><th style=\"width:160px\">Progress</th><th style=\"width:110px\"></th></tr></thead><tbody id=\"jobsbody\"></tbody></table></div>"
  "\n  </section>\n\n  <section id=\"tab-status\" style=\"display:none\">\n    <div class=\"stat\" id=\"statgrid\"></div>\n  </section>\n</main>\n\n<div id=\"detail\"><div class=\"box\" id=\"detailbox\"></div></div>\n<div clas"
  "s=\"flash\" id=\"flash\"></div>\n\n<script>\nlet CATALOG=[], curPath='/mnt';\n\n// ---- nav ----\ndocument.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{\n  document.querySelectorAll('nav button').for"
  "Each(x=>x.classList.remove('active'));\n  b.classList.add('active');\n  ['store','files','downloads','status'].forEach(t=>\n    document.getElementById('tab-'+t).style.display = t===b.dataset.tab\?'':'non"
  "e');\n  if(b.dataset.tab==='files') renderPanes();\n  if(b.dataset.tab==='downloads') refreshJobs();\n  if(b.dataset.tab==='status') loadStatus();\n  if(b.dataset.tab==='store') renderStore();\n});\n\nfuncti"
  "on flash(msg){const f=document.getElementById('flash');f.textContent=msg;f.style.display='block';setTimeout(()=>f.style.display='none',2600);}\nfunction esc(s){return String(s\?\?'').replace(/[&<>\"']/g,c"
  "=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]));}\nfunction fmtSize(n){if(n==null)return '—';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<4){n/=1024;i++;}return n.toF"
  "ixed(n>=100||i==0\?0:1)+' '+u[i];}\n\n// ---- store ----\nconst DIR_URL='https://pegasus-catalog.fly.dev/api/catalogs';\nasync function initCatalogDir(){\n  const sel=document.getElementById('catsel');\n  se"
  "l.innerHTML='<option value=\"\">loading sources…</option>';\n  try{\n    const r=await fetch(DIR_URL); const d=await r.json();\n    sel.innerHTML='<option value=\"\">— pick a source —</option>'+\n      (d.cat"
  "alogs||[]).map(c=>`<option value=\"${esc(c.sourceUrl)}\">${esc(c.name)} (${c.packageCount})</option>`).join('')+\n      '<option value=\"custom\">Custom URL…</option>';\n    // auto-load first\n    if((d.cat"
  "alogs||[]).length){ sel.selectedIndex=1; pickCatalog(); }\n  }catch(e){ sel.innerHTML='<option value=\"\">directory unreachable — use Custom URL</option>'; }\n}\nfunction pickCatalog(){\n  const sel=documen"
  "t.getElementById('catsel');\n  const u=document.getElementById('caturl');\n  if(sel.value==='custom'){ u.style.display=''; u.focus(); }\n  else if(sel.value){ u.style.display='none'; u.value=sel.value; l"
  "oadCatalog(); }\n}\nasync function loadCatalog(){\n  const url=document.getElementById('caturl').value.trim();\n  document.getElementById('catinfo').textContent='loading…';\n  try{\n    const r=await fetch("
  "url); const d=await r.json();\n    CATALOG=d.packages||[];\n    document.getElementById('catinfo').textContent=`${esc(d.name||'catalog')} — ${CATALOG.length} packages`;\n  }catch(e){document.getElementBy"
  "Id('catinfo').textContent='load failed: '+e.message;}\n  renderStore();\n}\nfunction renderStore(){\n  const q=document.getElementById('q').value.toLowerCase();\n  const g=document.getElementById('storegri"
  "d');\n  const list=CATALOG.filter(p=>!q||(p.title+' '+(p.titleId||'')+' '+(p.category||'')).toLowerCase().includes(q));\n  if(!list.length){g.innerHTML='<div class=\"empty\">No packages — load a catalog U"
  "RL above.</div>';return;}\n  g.innerHTML=list.slice(0,400).map((p,i)=>`\n    <div class=\"card\" onclick=\"showPkg(${CATALOG.indexOf(p)})\">\n      ${p.posterUrl\?`<img class=\"poster\" loading=\"lazy\" src=\"${es"
  "c(p.posterUrl)}\" onerror=\"this.style.visibility='hidden'\">`:'<div class=\"poster\"></div>'}\n      <div class=\"meta\"><div class=\"t\" title=\"${esc(p.title)}\">${esc(p.title)}</div>\n      <div class=\"s\">${es"
  "c(p.titleId||'')}${p.version\?' · v'+esc(p.version):''}</div></div>\n    </div>`).join('');\n}\nfunction showPkg(i){\n  const p=CATALOG[i]; if(!p)return;\n  document.getElementById('detailbox').innerHTML=`\n"
  "    <h2>${esc(p.title)}</h2>\n    <div class=\"sub\">${esc(p.titleId||'')} · ${esc(p.category||'')}${p.version\?' · v'+esc(p.version):''}</div>\n    ${p.description\?`<pre>${esc(p.description)}</pre>`:''}\n "
  "   ${(p.downloadLinks||[]).map((l,j)=>`\n      <div class=\"linkrow\"><span class=\"n\" title=\"${esc(l.url)}\">${esc(l.name||l.url)}</span>\n      <button class=\"btn small\" onclick=\"queueLink('${esc(l.url)}'"
  ")\">Queue</button></div>`).join('')}\n    ${p.downloadSource\?`<p style=\"margin-top:12px;color:var(--dim);font-size:12px\">source: ${esc(p.downloadSource)}</p>`:''}\n    <div style=\"margin-top:16px;text-al"
  "ign:right\"><button class=\"btn ghost\" onclick=\"closeDetail()\">Close</button></div>`;\n  document.getElementById('detail').style.display='flex';\n}\nfunction closeDetail(){document.getElementById('detail')"
  ".style.display='none';}\ndocument.getElementById('detail').onclick=e=>{if(e.target.id==='detail')closeDetail();};\n\n// ---- downloads ----\nasync function queueLink(url){\n  const dest=prompt('Download to"
  ":','/mnt/usb0'); if(!dest)return;\n  const r=await fetch('/api/fetch',{method:'POST',headers:{'Content-Type':'application/json'},\n    body:JSON.stringify({url,dest})});\n  flash(r.ok\?'Queued: '+url.slic"
  "e(0,60)+'…':'Queue failed'); closeDetail();\n}\nasync function queueManual(){\n  const url=document.getElementById('manualurl').value.trim();\n  const dest=document.getElementById('manualdest').value.trim"
  "()||'/mnt/usb0';\n  if(!url)return;\n  const r=await fetch('/api/fetch',{method:'POST',headers:{'Content-Type':'application/json'},\n    body:JSON.stringify({url,dest})});\n  flash(r.ok\?'Queued':'Queue fa"
  "iled');\n}\nasync function refreshJobs(){\n  try{\n    const r=await fetch('/api/jobs'); const j=await r.json();\n    document.getElementById('jobsbody').innerHTML=(j.jobs||[]).map(x=>{\n      const pct=x.t"
  "otal\?(x.bytes*100/x.total):0;\n      const st={'queued':'q','running':'run','done':'ok','error':'err'}[x.state]||'q';\n      const label={queued:'queued',running:'running',done:'done',error:'error'}[x.s"
  "tate]||x.state;\n      return `<tr><td>${x.id}</td><td style=\"max-width:420px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap\" title=\"${esc(x.url)}\">${esc(x.url)}</td>\n      <td><span class=\""
  "pill ${st}\">${label}</span></td>\n      <td><div style=\"display:flex;align-items:center;gap:8px\"><div class=\"bar\"><i style=\"width:${pct}%\"></i></div>\n      <span style=\"color:var(--dim);font-size:11.5p"
  "x;white-space:nowrap\">${fmtSize(x.bytes)}${x.total\?' / '+fmtSize(x.total):''}</span></div></td>\n      <td>${x.state==='error'\?`<span title=\"${esc(x.error||'')}\" style=\"color:var(--err);cursor:help\">\?<"
  "/span>`:''}</td></tr>`;\n    }).join('')||'<tr><td colspan=\"5\" class=\"empty\">No jobs</td></tr>';\n  }catch(e){}\n}\nsetInterval(()=>{if(document.getElementById('tab-downloads').style.display!=='none')refr"
  "eshJobs();},2000);\n\n// ---- files: dual-pane manager ----\nconst PANES=[{path:'/mnt'},{path:'/data'}];   // pane state\nlet activePane=0;                              // which pane an action targets\nlet"
  " lastPaneRender=[];\n\nfunction otherPane(i){return i===0\?1:0;}\nfunction parentOf(p){const i=p.lastIndexOf('/');return i<=0\?'/':p.slice(0,i);}\n\nasync function paneNav(i,path){\n  PANES[i].path=path;\n  co"
  "nst host=document.getElementById('pane'+i);\n  if(!host)return;\n  host.querySelector('.tbody').innerHTML='<tr><td colspan=\"4\" class=\"empty\">loading…</td></tr>';\n  try{\n    const r=await fetch('/api/fs/"
  "list\?path='+encodeURIComponent(path));\n    const d=await r.json();\n    if(d.error){host.querySelector('.tbody').innerHTML=`<tr><td colspan=\"4\" class=\"empty\">${esc(d.error)}</td></tr>`;return;}\n    las"
  "tPaneRender[i]=d.entries||[];\n    const rows=(d.entries||[]).map((e,ix)=>{\n      const full=(path==='/'\?'':path)+'/'+e.name;\n      return `<tr id=\"p${i}r${ix}\">\n        <td>${e.is_dir\n          \?`<spa"
  "n class=\"fname dir\" onclick=\"paneNav(${i},'${esc(full)}')\">${esc(e.name)}/</span>`\n          :`<span class=\"fname\" onclick=\"selRow(${i},${ix})\">${esc(e.name)}</span>`}</td>\n        <td style=\"color:va"
  "r(--dim)\">${e.is_dir\?'—':fmtSize(e.size)}</td>\n        <td style=\"color:var(--dim)\">${e.is_dir\?'dir':(e.name.split('.').pop()||'file')}</td>\n        <td>${e.is_dir\?'':`<a class=\"btn ghost small\" href="
  "\"/api/fs/download\?path=${encodeURIComponent(full)}\">get</a>`}</td></tr>`;\n    }).join('');\n    host.querySelector('.tbody').innerHTML=rows||'<tr><td colspan=\"4\" class=\"empty\">Empty</td></tr>';\n  }catc"
  "h(e){host.querySelector('.tbody').innerHTML=`<tr><td colspan=\"4\" class=\"empty\">error: ${esc(e.message)}</td></tr>`;}\n}\n\nlet selected={};  // pane -> full path of selected file\nfunction selRow(i,ix){\n "
  " const e=(lastPaneRender[i]||[])[ix]; if(!e)return;\n  selected[i]=(PANES[i].path==='/'\?'':PANES[i].path)+'/'+e.name;\n  document.querySelectorAll(`#pane${i} tr`).forEach(tr=>tr.style.background='');\n  "
  "const tr=document.getElementById(`p${i}r${ix}`); if(tr)tr.style.background='var(--panel2)';\n}\n\nfunction paneActions(i){\n  const src=selected[i], dst=PANES[otherPane(i)].path;\n  return `\n   <button cla"
  "ss=\"btn small\" ${src\?'':'disabled style=\"opacity:.45\"'} onclick=\"fsOp('copy',${i})\">Copy →</button>\n   <button class=\"btn small\" ${src\?'':'disabled style=\"opacity:.45\"'} onclick=\"fsOp('move',${i})\">Mo"
  "ve →</button>\n   <button class=\"btn small ghost\" onclick=\"paneMkdir(${i})\">+Folder</button>\n   <button class=\"btn small ghost\" style=\"color:var(--err)\" ${src\?'':'disabled style=\"opacity:.45\"'} onclick"
  "=\"paneDelete(${i})\">Delete</button>`;\n}\n\nasync function fsOp(op,i){\n  const src=selected[i]; if(!src)return flash('select a file first');\n  const dst=PANES[otherPane(i)].path;\n  if(!confirm(`${op} ${s"
  "rc} → ${dst}\?`))return;\n  const r=await fetch('/api/fs/'+op,{method:'POST',headers:{'Content-Type':'application/json'},\n    body:JSON.stringify({src,dst_dir:dst})});\n  const d=await r.json().catch(()="
  ">({}));\n  flash(d.ok\?`${op} done`:('failed: '+(d.error||r.status)));\n  delete selected[i]; paneNav(i,PANES[i].path); paneNav(otherPane(i),PANES[otherPane(i)].path);\n}\nasync function paneMkdir(i){\n  co"
  "nst name=prompt('New folder name:'); if(!name)return;\n  const p=(PANES[i].path==='/'\?'':PANES[i].path)+'/'+name;\n  const r=await fetch('/api/fs/mkdir',{method:'POST',headers:{'Content-Type':'applicati"
  "on/json'},body:JSON.stringify({path:p})});\n  const d=await r.json().catch(()=>({}));\n  flash(d.ok\?'created':'failed: '+(d.error||r.status));\n  paneNav(i,PANES[i].path);\n}\nasync function paneDelete(i){"
  "\n  const src=selected[i]; if(!src)return flash('select a file first');\n  if(!confirm('Delete '+src+'\? This cannot be undone.'))return;\n  const r=await fetch('/api/fs/delete',{method:'POST',headers:{'C"
  "ontent-Type':'application/json'},body:JSON.stringify({path:src})});\n  const d=await r.json().catch(()=>({}));\n  flash(d.ok\?'deleted':'failed: '+(d.error||r.status));\n  delete selected[i]; paneNav(i,PA"
  "NES[i].path);\n}\n\nfunction renderPanes(){\n  const dp=document.getElementById('dualpane');\n  dp.innerHTML=[0,1].map(i=>`\n    <div class=\"panel\" id=\"pane${i}\" style=\"padding:14px\">\n      <div class=\"row\""
  " style=\"margin-bottom:10px\">\n        <button class=\"btn ghost small\" onclick=\"paneNav(${i},'/mnt')\">/mnt</button>\n        <button class=\"btn ghost small\" onclick=\"paneNav(${i},'/data')\">/data</button>"
  "\n        <button class=\"btn ghost small\" onclick=\"paneNav(${i},'/')\">/</button>\n        <button class=\"btn ghost small\" onclick=\"paneNav(${i},parentOf(PANES[${i}].path))\">↑</button>\n        <span styl"
  "e=\"margin-left:auto\">${paneActions(i)}</span>\n      </div>\n      <div class=\"crumbs\"><b id=\"pp${i}\"></b></div>\n      <table><thead><tr><th>Name</th><th style=\"width:90px\">Size</th><th style=\"width:80p"
  "x\">Type</th><th style=\"width:60px\"></th></tr></thead>\n      <tbody class=\"tbody\"></tbody></table>\n    </div>`).join('');\n  [0,1].forEach(i=>{paneNav(i,PANES[i].path);\n    setInterval(()=>{const el=doc"
  "ument.getElementById('pp'+i);if(el)el.textContent=PANES[i].path;},400);});\n}\nfunction nav(path){paneNav(activePane,path);}  // legacy hook\n\n// ---- status ----\nasync function loadStatus(){\n  try{\n    "
  "const r=await fetch('/status'); const d=await r.json();\n    document.getElementById('statgrid').innerHTML=Object.entries(d).map(([k,v])=>\n      `<div class=\"kv\"><div class=\"k\">${esc(k)}</div><div clas"
  "s=\"v\">${esc(v)}</div></div>`).join('');\n  }catch(e){document.getElementById('statgrid').innerHTML='<div class=\"empty\">offline\?</div>';}\n}\n\ninitCatalogDir();\n</script>\n</body>\n</html>\n"
;
#define UI_HTML_LEN 18420
#endif
